[repository]
name = "hyprmodoro"
authors = ["0xFMD"]
commit_pins = [
  ["f7aae0b2a7811815ffbab7ab10a4ddaae71e36e1", "348c1624fac6c93f57a06902e7ef2c0775515a73"],    # Hyprland v0.50.1
]

[hyprmodoro]
description = "A Pomodoro timer plugin for Hyprland"
authors = ["0xFMD"]
output = "hyprmodoro.so"
build = ["make all"]